import { useUiStore } from '@/stores/ui'

/**
 * Registers the service worker generated by vite-plugin-pwa and shows a
 * toast when a new version is ready, offering the user a one-click reload.
 * No-ops gracefully in dev mode or environments without SW support.
 */
export function usePwaUpdate() {
  if (import.meta.env.DEV || !('serviceWorker' in navigator)) return

  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      const ui = useUiStore()
      registerSW({
        immediate: true,
        onNeedRefresh() {
          ui.pushToast({ type: 'success', message: 'A new version is available — refresh to update.' })
        },
        onOfflineReady() {
          ui.pushToast({ type: 'success', message: 'Nexora Company is ready to work offline.' })
        },
      })
    })
    .catch(() => {
      /* PWA plugin virtual module unavailable (e.g. during certain dev setups) — ignore */
    })
}
